-- ============================================================================
-- Defensive Driving — Phase 4 final exam engine (server-validated)
-- ----------------------------------------------------------------------------
--   dd_start_exam(course)        -> gate, enforce retake limit + cooldown,
--                                   create an attempt, return a randomized
--                                   subset of the final pool with shuffled
--                                   choices and NO correct keys.
--   dd_submit_exam(attempt, ans) -> score server-side over the SERVED question
--                                   set, record the attempt, and on pass mark
--                                   the enrollment 'completed'.
--
-- The certificate PDF is generated by the dd-issue-certificate Edge Function
-- (pdf-lib needs the Deno runtime); inserting dd_certificates fires the
-- existing trigger that pushes the row into dd_discount_queue.
-- ============================================================================

-- Record which questions were served, so scoring is over the served set
-- (a client cannot omit hard questions to inflate its score).
ALTER TABLE dd_exam_attempts ADD COLUMN IF NOT EXISTS question_ids UUID[];

CREATE OR REPLACE FUNCTION dd_start_exam(p_course_id UUID)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_enr UUID;
  v_min_seat INT; v_qcount INT; v_retake INT; v_cooldown INT;
  v_modules INT; v_completed INT; v_seat INT;
  v_attempts INT; v_last_submit TIMESTAMPTZ; v_passed BOOLEAN;
  v_attempt_no INT; v_attempt_id UUID;
  v_qids UUID[]; v_questions JSONB;
BEGIN
  SELECT e.id INTO v_enr FROM dd_enrollments e
   WHERE e.course_id = p_course_id AND e.user_id = auth.uid()
     AND e.status IN ('active', 'completed')
   LIMIT 1;
  IF v_enr IS NULL THEN RAISE EXCEPTION 'no enrollment'; END IF;

  SELECT min_seat_seconds, exam_question_count, retake_limit, retake_cooldown_seconds
    INTO v_min_seat, v_qcount, v_retake, v_cooldown
    FROM dd_courses WHERE id = p_course_id;

  -- Unlock: every module completed AND total seat time met.
  SELECT COUNT(*) INTO v_modules FROM dd_modules WHERE course_id = p_course_id;
  SELECT COUNT(*) FILTER (WHERE mp.completed_at IS NOT NULL),
         COALESCE(SUM(mp.seconds_spent), 0)
    INTO v_completed, v_seat
    FROM dd_modules m
    LEFT JOIN dd_module_progress mp ON mp.module_id = m.id AND mp.enrollment_id = v_enr
   WHERE m.course_id = p_course_id;
  IF v_completed < v_modules OR v_seat < v_min_seat THEN
    RAISE EXCEPTION 'exam locked';
  END IF;

  SELECT EXISTS (SELECT 1 FROM dd_exam_attempts WHERE enrollment_id = v_enr AND passed) INTO v_passed;
  IF v_passed THEN RAISE EXCEPTION 'already passed'; END IF;

  SELECT COUNT(*), MAX(submitted_at) INTO v_attempts, v_last_submit
    FROM dd_exam_attempts WHERE enrollment_id = v_enr;
  IF v_attempts >= v_retake THEN RAISE EXCEPTION 'no attempts remaining'; END IF;
  IF v_last_submit IS NOT NULL
     AND v_last_submit + make_interval(secs => v_cooldown) > now() THEN
    RAISE EXCEPTION 'cooldown active';
  END IF;

  -- Randomized subset of the final pool with shuffled choices, no keys.
  SELECT array_agg(s.id),
         jsonb_agg(jsonb_build_object(
           'id', s.id, 'qtype', s.qtype, 'prompt', s.prompt,
           'choices', (SELECT jsonb_agg(c ORDER BY random()) FROM jsonb_array_elements(s.choices) c)
         ))
    INTO v_qids, v_questions
  FROM (
    SELECT id, qtype, prompt, choices
      FROM dd_questions
     WHERE course_id = p_course_id AND module_id IS NULL AND is_active = true
     ORDER BY random()
     LIMIT v_qcount
  ) s;

  v_attempt_no := v_attempts + 1;
  INSERT INTO dd_exam_attempts (enrollment_id, attempt_no, started_at, question_ids)
  VALUES (v_enr, v_attempt_no, now(), v_qids)
  RETURNING id INTO v_attempt_id;

  RETURN jsonb_build_object(
    'attempt_id', v_attempt_id,
    'attempt_no', v_attempt_no,
    'question_count', COALESCE(array_length(v_qids, 1), 0),
    'questions', v_questions
  );
END;
$$;

CREATE OR REPLACE FUNCTION dd_submit_exam(p_attempt_id UUID, p_answers JSONB)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_enr UUID; v_qids UUID[]; v_submitted TIMESTAMPTZ; v_course UUID;
  v_threshold INT; v_retake INT; v_cooldown INT;
  v_total INT; v_correct INT; v_score NUMERIC; v_pass BOOLEAN;
  v_attempts INT; v_remaining INT; v_cooldown_until TIMESTAMPTZ;
BEGIN
  SELECT a.enrollment_id, a.question_ids, a.submitted_at, e.course_id
    INTO v_enr, v_qids, v_submitted, v_course
    FROM dd_exam_attempts a
    JOIN dd_enrollments e ON e.id = a.enrollment_id
   WHERE a.id = p_attempt_id AND e.user_id = auth.uid();
  IF v_enr IS NULL THEN RAISE EXCEPTION 'attempt not found'; END IF;
  IF v_submitted IS NOT NULL THEN RAISE EXCEPTION 'attempt already submitted'; END IF;

  SELECT pass_threshold_pct, retake_limit, retake_cooldown_seconds
    INTO v_threshold, v_retake, v_cooldown FROM dd_courses WHERE id = v_course;

  v_total := COALESCE(array_length(v_qids, 1), 0);
  IF v_total = 0 THEN RAISE EXCEPTION 'invalid attempt'; END IF;

  SELECT COUNT(*) FILTER (WHERE p_answers->>(q.id::text) = q.correct_key)
    INTO v_correct FROM dd_questions q WHERE q.id = ANY(v_qids);

  v_score := ROUND((v_correct::numeric / v_total) * 100, 2);
  v_pass := v_score >= v_threshold;

  UPDATE dd_exam_attempts
     SET score_pct = v_score, passed = v_pass, submitted_at = now(), answers = p_answers
   WHERE id = p_attempt_id;

  IF v_pass THEN
    UPDATE dd_enrollments
       SET status = 'completed', completed_at = COALESCE(completed_at, now())
     WHERE id = v_enr;
  END IF;

  SELECT COUNT(*) INTO v_attempts FROM dd_exam_attempts WHERE enrollment_id = v_enr;
  v_remaining := GREATEST(0, v_retake - v_attempts);
  IF NOT v_pass AND v_remaining > 0 THEN
    v_cooldown_until := now() + make_interval(secs => v_cooldown);
  END IF;

  RETURN jsonb_build_object(
    'score_pct', v_score, 'passed', v_pass, 'threshold', v_threshold,
    'total', v_total, 'correct', v_correct,
    'attempts_used', v_attempts, 'attempts_remaining', v_remaining,
    'cooldown_until', v_cooldown_until
  );
END;
$$;

REVOKE ALL ON FUNCTION dd_start_exam(UUID)         FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION dd_submit_exam(UUID, JSONB) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION dd_start_exam(UUID)         TO authenticated;
GRANT EXECUTE ON FUNCTION dd_submit_exam(UUID, JSONB) TO authenticated;
