-- Add missing Bland webhook audit event types to the constraint.
-- These are needed by bland-webhook (not yet built) to log call outcomes.
ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_event_type_check;
ALTER TABLE audit_log ADD CONSTRAINT audit_log_event_type_check
  CHECK (event_type IN (
    'LEAD_CREATED', 'ROUTED', 'NOTIFIED', 'ROUTING_FALLBACK',
    'STATUS_CHANGED', 'ASSIGNED', 'LEAD_STATUS_UPDATED',
    'LEAD_DISPOSED',
    'SMS_SENT', 'SMS_INBOUND', 'SMS_DRIP_SENT', 'SMS_DRIP_FAILED', 'SMS_MANUAL_SENT',
    'CALL_INITIATED', 'CALL_CONNECTED', 'CALL_MISSED',
    'CANOPY_WEBHOOK_RECEIVED', 'ENRICHMENT_ORPHAN_PULL',
    'ENRICHMENT_STARTED', 'ENRICHMENT_SUCCEEDED', 'ENRICHMENT_FAILED',
    'AGENT_AVAILABILITY_ON',
    'AGENT_AVAILABILITY_OFF',
    'AGENT_AVAILABILITY_AUTO_RESET',
    'AGENT_TRANSFER_PHONE_SET',
    'BLAND_OUTBOUND_INITIATED',
    'BLAND_OUTBOUND_FAILED',
    'BLAND_OUTBOUND_TRANSFERRED',
    'BLAND_TRANSFER_MISSED',
    'LEAD_QUALIFIED_BLAND',
    'LEAD_DISQUALIFIED_BLAND',
    'BLAND_INBOUND_TRANSFERRED',
    'BLAND_CALLBACK_REQUESTED',
    'BLAND_WEBHOOK_ERROR',
    'CANOPY_LINK_SENT_BLAND'
  ));
